name: mafia_board
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  #ui
  cupertino_icons: ^1.0.2
  fl_chart: ^0.64.0

  #bloc
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^9.1.3

  #common
  get_it: ^7.3.0
  rxdart: ^0.27.7
  collection: ^1.16.0
  class_to_string: ^0.0.3
  http: ^1.1.0
  uuid: ^4.1.0
  url_launcher: 6.1.13
  shared_preferences: ^2.2.2

  #firebase
  cloud_firestore: ^4.13.5
  firebase_auth: ^4.15.2
  firebase_core: ^2.24.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true